[build]
builder = "NIXPACKS"
buildCommand = "pnpm install && pnpm build"

[deploy]
startCommand = "pnpm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
name = "api"
source = "apps/api"
buildCommand = "pnpm install && pnpm --filter @makeabet/api build"
startCommand = "pnpm --filter @makeabet/api start"

[[services.env]]
name = "NODE_ENV"
value = "production"

[[services.env]]
name = "PORT"
value = "4000"

[[services]]
name = "web"
source = "apps/web"
buildCommand = "pnpm install && pnpm --filter @makeabet/web build"
startCommand = "pnpm --filter @makeabet/web preview"

[[services.env]]
name = "NODE_ENV"
value = "production"
